# Generated by Django 5.1.3 on 2024-12-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_author_user_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='وضیعت نویسندگی'),
        ),
    ]
